[package]
name = "asyou_rust_sdk"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# 基础依赖
env_logger = "0.9"
log = "0.4"
slab = "0.4"
serde = "1.0.143"
serde_json = "1.0.83"
base64 = "0.13.0"
async-std = "1.12.0"

# 业务处理
tokio = {version = "1.20.1", features = ["full"]}
once_cell = "1.13.0"
chrono = "0.4.19"
thiserror = "1.0.31"
anyhow = "1.0.58"
sqlx = {version = "0.6.0", default-features = false, features = ["runtime-tokio-rustls", "mysql", "macros", "chrono"]}
futures = "0.3.13"
tracing-subscriber = "0.3.11"
reqwest = { version = "0.11.11" }
blake3 = "1.3.1"

# 区块链
# subxt = {git = "https://github.com/paritytech/subxt", branch = "na-wasm-support"} 
subxt = "0.24.0"
# subxt-codegen = "0.24.0"
sp-core = { version = "6.0.0", default-features = false  }
sp-keyring = "6.0.0"
sp-runtime = "6.0.0"
ink_env = "3.3.0"
ink_prelude ={version = "3", default-features = false}
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
hex = "0.4.3"

[profile.release]
opt-level = 3

[[example]]
name = "main"
path = "examples/main.rs"

# [[example]]
# name = "trace_source"
# path = "examples/trace_source.rs"

# [[example]]
# name = "feeless"
# path = "examples/feeless.rs"